In [2]:
import torch

In [8]:
x = torch.tensor([[10,20,30,40],[50,60,70,80]])
x.shape

torch.Size([2, 4])

In [10]:
x = torch.tensor([[10,20,30,40],[50,60,70,80]])
x.shape

torch.Size([2, 4])

In [12]:
x.add(10)

tensor([[20, 30, 40, 50],
        [60, 70, 80, 90]])

In [14]:
x.shape

torch.Size([2, 4])

In [16]:
x.view(4,2) #muda as dimensoes

tensor([[10, 20],
        [30, 40],
        [50, 60],
        [70, 80]])

In [18]:
a = torch.ones(2,1,10) # creating a 2x1x10 tensor full of 1's
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [20]:
x = torch.tensor([[10,20,30,40],[50,60,70,80]]) # Shape = (2,4)
y = torch.tensor([[10,20,30],
                  [40,50,60],
                  [70,80,90],
                  [100,110,120]]) # Shape = (4,3)

In [22]:
torch.matmul(x,y)

tensor([[ 7000,  8000,  9000],
        [15800, 18400, 21000]])

In [24]:
x = torch.randn(1,4,5)
z = torch.cat([x,x], axis = 1)
print('Concatenated axis 1:', x.shape, z.shape)

Concatenated axis 1: torch.Size([1, 4, 5]) torch.Size([1, 8, 5])
