In [3]:
import torch

In [4]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
x.shape

torch.Size([2, 4])

In [7]:
c

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [9]:
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [11]:
x.shape

torch.Size([2, 4])

In [13]:
x.view(4,2) #muda as dimensoes

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [15]:
a = torch.ones(2,1,10) # creating a 2x1x10 tensor full of 1's
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [17]:
print(f"Esta é a forma (shape) antes de aplicar o squeeze: {a.shape}")
squeezed = a.squeeze(1)
print(f"Esta é a forma (shape) depois de aplicar o squeeze: {squeezed.shape}")

# O resultado é o mesmo tensor, mas sem a i-ésima dimensão (neste caso, a primeira dimensão, considerando
# que a contagem começa a partir de zero).


Esta é a forma (shape) antes de aplicar o squeeze: torch.Size([2, 1, 10])
Esta é a forma (shape) depois de aplicar o squeeze: torch.Size([2, 10])


In [19]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]]) # Shape = (2,4)
y = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]]) # Shape = (4,3)

In [21]:
torch.matmul(x,y)

tensor([[ 70,  80,  90],
        [158, 184, 210]])

In [23]:
x = torch.randn(1,4,5)
z = torch.cat([x,x], axis = 1)
print('Concatenated axis 1:', x.shape, z.shape)

Concatenated axis 1: torch.Size([1, 4, 5]) torch.Size([1, 8, 5])


In [25]:
x = torch.randn(3,20,10)
z = x.permute(2,0,1) # changes the dimensions of the first elemento to the last, last to the second, etc
print('Permute dimensions:', x.shape, z.shape)

Permute dimensions: torch.Size([3, 20, 10]) torch.Size([10, 3, 20])
